services:
  frontend:
    image: iousco/trouvetonmatch-frontend:0.0.1
    depends_on:
      backend:
        condition: service_healthy
    ports:
      - "3000:80"
    environment:
      - API_URL = backend:8080
    networks:
      - app-network

  backend:
    image: iousco/trouvetonmatch-backend:0.0.1
    depends_on:
      - db
    volumes:
      - uploads:/app/uploads
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/match
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
    env_file:
      - .env
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--spider", "http://backend:8080/api/actuator/health"]

      interval: 30s
      timeout: 20s
      retries: 3
    networks:
      - app-network

  db:
    image: postgres:15
    container_name: pg_db
    restart: always
    environment:
      POSTGRES_DB: match
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - app-network

volumes:
  pgdata:
  uploads:

networks:
  app-network:
    driver: bridge
