version: '3.8'

services:
    app:
      build:
        context: .
        dockerfile: Dockerfile
      depends_on:
        - db
      ports:
        - "8080:8080"
      environment:
        SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/match
        SPRING_DATASOURCE_USERNAME: postgres
        SPRING_DATASOURCE_PASSWORD: postgres
        SPRING_JPA_HIBERNATE_DDL_AUTO: update

    db:
      image: postgres:15
      container_name: pg_db
      restart: always
      environment:
        POSTGRES_DB: match
        POSTGRES_USER: postgres
        POSTGRES_PASSWORD: postgres
      volumes:
        - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
