CREATE TABLE adresse
(
    id      BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    rue     VARCHAR(255),
    cpostal VARCHAR(255),
    ville   VARCHAR(255),
    CONSTRAINT pk_adresse PRIMARY KEY (id)
);

CREATE TABLE parrain
(
    id             BIGINT NOT NULL,
    parcours       VARCHAR(255),
    expertise      VARCHAR(255),
    deplacements   VARCHAR(255),
    disponibilites VARCHAR(255),
    CONSTRAINT pk_parrain PRIMARY KEY (id)
);

CREATE TABLE plateforme
(
    id         BIGINT NOT NULL,
    nom        VARCHAR(255),
    telephone  VARCHAR(255),
    CONSTRAINT pk_plateforme PRIMARY KEY (id)
);

CREATE TABLE porteur
(
    id            BIGINT NOT NULL,
    disponibilite VARCHAR(255),
    projet_id     BIGINT,
    CONSTRAINT pk_porteur PRIMARY KEY (id)
);

CREATE TABLE project
(
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    starting_date date,
    title         VARCHAR(255),
    description   VARCHAR(255),
    CONSTRAINT pk_project PRIMARY KEY (id)
);

CREATE TABLE utilisateur
(
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    username      VARCHAR(255)                            NOT NULL,
    password      VARCHAR(255)                            NOT NULL,
    email         VARCHAR(255)                            NOT NULL,
    role          VARCHAR(255),
    plateforme_id BIGINT,
    adresse_id    BIGINT,
    CONSTRAINT pk_utilisateur PRIMARY KEY (id)
);

ALTER TABLE plateforme
    ADD CONSTRAINT FK_PLATEFORME_ON_ID FOREIGN KEY (id) REFERENCES utilisateur (id);

ALTER TABLE utilisateur
    ADD CONSTRAINT uc_utilisateur_email UNIQUE (email);

ALTER TABLE utilisateur
    ADD CONSTRAINT uc_utilisateur_username UNIQUE (username);

ALTER TABLE parrain
    ADD CONSTRAINT FK_PARRAIN_ON_ID FOREIGN KEY (id) REFERENCES utilisateur (id);

ALTER TABLE porteur
    ADD CONSTRAINT FK_PORTEUR_ON_ID FOREIGN KEY (id) REFERENCES utilisateur (id);

ALTER TABLE porteur
    ADD CONSTRAINT FK_PORTEUR_ON_PROJET FOREIGN KEY (projet_id) REFERENCES project (id);

ALTER TABLE utilisateur
    ADD CONSTRAINT FK_UTILISATEUR_ON_ADRESSE FOREIGN KEY (adresse_id) REFERENCES adresse (id);

ALTER TABLE utilisateur
    ADD CONSTRAINT FK_UTILISATEUR_ON_PLATEFORME FOREIGN KEY (plateforme_id) REFERENCES plateforme (id);