CREATE TABLE documents
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name        VARCHAR(255) NOT NULL ,
    type        VARCHAR(255) NOT NULL ,
    path        VARCHAR(255) NOT NULL ,
    uploaded_at TIMESTAMP WITHOUT TIME ZONE DEFAULT NOW(),
    uploaded_by BIGINT,
    CONSTRAINT pk_document PRIMARY KEY (id),
    CONSTRAINT fk_uploaded_by FOREIGN KEY (uploaded_by) REFERENCES utilisateur (id) ON DELETE SET NULL
);

INSERT INTO documents (name, type, path, uploaded_by)
VALUES ('Sample document 1', 'application/pdf', 'docs/sample-1.pdf', 10),
       ('Sample document 2', 'application/pdf', 'docs/sample-2.pdf', 10),
       ('Sample document 3', 'application/pdf', 'docs/sample-3.pdf', 10),
       ('Sample document 4', 'application/pdf', 'docs/sample-4.pdf', 10),
       ('Sample document 5', 'application/pdf', 'docs/sample-5.pdf', 10),
       ('Sample document 6', 'application/zip', 'docs/sample-1.zip', 10);