CREATE TABLE compte_rendu
(
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    date_echange  date,
    heure_echange time WITHOUT TIME ZONE,
    moyen_echange VARCHAR(255),
    sujets        VARCHAR(255),
    resume        VARCHAR(2000),
    actionsamener VARCHAR(2000),
    prochain_rdv  date,
    porteur_id    BIGINT,
    CONSTRAINT pk_compte_rendu PRIMARY KEY (id)
);

ALTER TABLE compte_rendu
    ADD CONSTRAINT FK_COMPTE_RENDU_ON_PORTEUR FOREIGN KEY (porteur_id) REFERENCES porteur (id);