name: Deploy to NAS DS224+

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build Docker image
        run: |
          docker compose build
      - name: Install sshpass
        run: |
          sudo apt-get update
          sudo apt-get install -y sshpass
      - name: Push to NAS DS224+
        run: |
          sshpass -p "${{ secrets.NAS_PASSWORD }}" ssh ${{ secrets.NAS_USER }}@${{ secrets.NAS }} "docker stop trouvetonmatch || true"
          rsync -avz -e "sshpass -p '${{ secrets.NAS_PASSWORD }}' ssh" . ${{ secrets.NAS_USER }}@${{ secrets.NAS }}:/volume1/docker/trouvetonmatch
          sshpass -p "${{ secrets.NAS_PASSWORD }}" ssh ${{ secrets.NAS_USER }}@${{ secrets.NAS }} "[[ -f /volume1/docker/trouvetonmatch/docker-compose.yml ]] && cd /volume1/docker/trouvetonmatch && docker-compose up -d --build"