name: Deploy to NAS DS224+

on:
  push:
    branches:
      - main
permissions:
  contents: write
  packages: write

env:
  FOLDER: /volume1/docker/trouvetonmatch
  IMAGE: trouvetonmatch
  VERSION: 0.0.1

jobs:
  create-folder:
    name: create folder
    runs-on: ubuntu-latest
    steps:
      - name: run step create folder
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.NAS }}
          username: ${{ secrets.NAS_USER }}
          key: ${{ secrets.DEPLOY_SSH_KEY }}
          script: |
            mkdir -p ${{env.FOLDER}}
            ls -al ${{env.FOLDER}}

  build-push-dockerhub:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build Docker image
        working-directory: ${{ github.workspace }}
        run: docker compose -f docker-compose-build.yml build
      - name: List Docker images
        run: docker images
      - name: Check available images
        run: docker images
      - name: Push Docker images
        working-directory: ${{ github.workspace }}
        run: |
          docker tag trouvetonmatch-backend:latest ${{ secrets.DOCKERHUB_USERNAME }}/${{env.IMAGE}}-backend:${{env.VERSION}}
          docker tag trouvetonmatch-frontend:latest ${{ secrets.DOCKERHUB_USERNAME }}/${{env.IMAGE}}-frontend:${{env.VERSION}}
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/${{env.IMAGE}}-backend:${{env.VERSION}}
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/${{env.IMAGE}}-frontend:${{env.VERSION}}
    
  run-container:
    name: run container
    runs-on: ubuntu-latest
    needs: [create-folder, build-push-dockerhub]
    steps:
      - name: checkout code
        uses: actions/checkout@master
      - name: List files in the current folder
        run: ls -al
      - name: copy docker-compose to ssh
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.NAS }}
          username: ${{ secrets.NAS_USER }}
          key: ${{ secrets.DEPLOY_SSH_KEY }}
          source: "docker-compose-nas.yml"
          target: ${{env.FOLDER}}
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: run container
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.NAS }}
          username: ${{ secrets.NAS_USER }}
          key: ${{ secrets.DEPLOY_SSH_KEY }}
          script: |
            cd ${{env.FOLDER}}
            echo SPRING_SECURITY_JWT_SECRET=${{ secrets.SPRING_SECURITY_JWT_SECRET }} >> .env
            echo SPRING_MAIL_HOST=${{ secrets.SPRING_MAIL_HOST }} >> .env
            echo SPRING_MAIL_USER=${{ secrets.SPRING_MAIL_USER }} >> .env
            echo SPRING_MAIL_PASSWORD=${{ secrets.SPRING_SECURITY_JWT_SECRET }} >> .env
            echo SPRING_PROFILES_ACTIVE=${{ secrets.SPRING_PROFILES_ACTIVE }} >> .env
            echo SPRING_DATASOURCE_URL=${{ secrets.SPRING_DATASOURCE_URL }} >> .env
            echo SPRING_DATASOURCE_USERNAME=${{ secrets.SPRING_DATASOURCE_USERNAME }} >> .env
            echo SPRING_DATASOURCE_PASSWORD=${{ secrets.SPRING_DATASOURCE_PASSWORD }} >> .env
            echo SPRING_JPA_HIBERNATE_DDL_AUTO=${{ secrets.SPRING_JPA_HIBERNATE_DDL_AUTO }} >> .env
            echo POSTGRES_DB=${{ secrets.POSTGRES_DB }} >> .env
            echo POSTGRES_USER=${{ secrets.POSTGRES_USER }} >> .env
            echo POSTGRES_PASSWORD=${{ secrets.POSTGRES_PASSWORD }} >> .env
            export PATH=$PATH:/usr/local/bin
            docker pull ${{ secrets.DOCKERHUB_USERNAME }}/${{env.IMAGE}}-backend:${{env.VERSION}}
            docker pull ${{ secrets.DOCKERHUB_USERNAME }}/${{env.IMAGE}}-frontend:${{env.VERSION}}
            docker-compose down -v
            docker-compose -f docker-compose-nas.yml up -d